### PR TITLE
Add requirements around scopes

### PR DESCRIPTION
**Pull request by rhyssmith**

### CODE REVIEW

**Comment by ghalse** [comment]
I'm concerned by "by DNS domain names", since that implies that the RHS of a scoped attribute *must* exist in DNS. We have entities who use scoped attributes that, whilst structured like DNS within a domain they own, are not actually registered in DNS. We use wording along the lines of "a syntactically valid (pseudo-)subdomain within the bailiwick of a DNS domain owned by the entity".

**Comment by br00k** [comment]
Maybe if the line: 

> Identity Provider entities, scopes MUST be named by DNS domain names, 

to:

> Identity Provider entities, scopes MUST be ***rooted in the*** DNS domain name ***space***, 

it allows the scopes to begin with DNS domain names but there can be left most extensions that aren't listed.

**Comment by ghalse** [comment]
@peter- bailiwick is a term widely used in DNS, but point taken. I like @br00k's version.

**Comment by rhyssmith** [comment]
Yeah, what @peter said - this is just a guide. UKf also has exceptions for schools where we generate synthetic scopes (see s 4.2 of https://www.ukfederation.org.uk/doc/mdrps-20130902 ).

Happy with @brook's "rooted in the DNS domain name space" though.

**Comment by rhyssmith** [comment]
Suggested change made in this PR.

**Comment by nicoleharris** [comment]
merged.

**Pull request merged**
